version: '3'

services:
  mysql:
    restart: always
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=calli
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "1"
    # command: >

  adminer:
    image: adminer
    restart: always
    labels:
      - "traefik.http.routers.adminer.rule=Host(`adminer.de.v`)"
    ports:
      - 20081:8080

networks: 
  default:
    external:
      name: calli

volumes:
  mysql_data:
    external: true